### PR TITLE
Adding mailing lists file under collaboration

### PR DESCRIPTION
**Pull request by ecamellini**

### CODE REVIEW

**Comment by ecamellini** [comment]
@giogonzo I moved the reference to mailing lists here. However, GAPS doesn't seem to work (404 when I click `Sign In`); we could fix it or remove it

**Comment by giogonzo** [comment]
/ccing @gabro or @lucacioria here, not sure what's the state of the art

**Comment by lucacioria** [comment]
tl;dr => IMO discard this PR because mailing lists are not used

To be honest, nobody used those.. I would not write this in the book.
If someone think they are useful, please organize a small retrospective about information sharing tools (email, slack, standup, meeting videos, weekly recaps) so that we can make it clearer.

**Comment by lucacioria** [comment]
btw, I would remove any other reference to project mailing lists, the only ones that we actually use are like work@buildo... team@banksealer (this is not a buildo-wide thing though)..

**Comment by ecamellini** [comment]
@lucacioria yeah that's what I though too, but I was not sure. Btw I already removed the reference to mailing lists in the CoC page (and moved it in this PR). I don't think there are other references to them in the book

**Comment by giogonzo** [comment]
ok, then closing this. Thanks @ecamellini !

**Pull request closed without merging**
